apiVersion: v1
kind: ConfigMap
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
data:
  log_collection_settings.json: |-
    {
      "log_collection_settings": {
        "stdout": {
          "enabled": true,
          "namespaces": ["hetairoi", "kube-system"]
        },
        "stderr": {
          "enabled": true,
          "namespaces": ["hetairoi", "kube-system"]
        }
      }
    }